# Generated by Django 5.2.17 on 2026-10-02 06:40

import django.core.validators
import django.db.models.deletion
import frontend.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=32, unique=True)),
                ('full_name', models.CharField(max_length=160)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('nationality', models.CharField(blank=True, max_length=80)),
                ('job_title', models.CharField(blank=True, max_length=120)),
                ('client_name', models.CharField(blank=True, max_length=160)),
                ('origin_country', models.CharField(default='Nepal', max_length=80)),
                ('destination', models.CharField(default='Dubai, UAE', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('on_leave', 'On leave'), ('completed', 'Completed')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_employees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name', 'employee_id'],
            },
        ),
        migrations.CreateModel(
            name='BillingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=40, unique=True)),
                ('client_name', models.CharField(max_length=160)),
                ('description', models.CharField(max_length=240)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='AED', max_length=3)),
                ('bill_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='draft', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_billing_records', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_records', to='frontend.employee')),
            ],
            options={
                'ordering': ['-bill_date', 'invoice_number'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('passport', 'Passport'), ('photo', 'Photo'), ('contract', 'Contract'), ('other', 'Other')], default='other', max_length=16)),
                ('file', models.FileField(upload_to=frontend.models.employee_document_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='frontend.employee')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_employee_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='HiringRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=160)),
                ('hiring_person_name', models.CharField(max_length=160)),
                ('hiring_person_employee_id', models.CharField(blank=True, max_length=32)),
                ('joining_date', models.DateField()),
                ('destination', models.CharField(default='Dubai, UAE', max_length=100)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('confirmed', 'Confirmed'), ('arrived', 'Arrived')], default='new', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hiring_records', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='joinings', to='frontend.employee')),
            ],
            options={
                'ordering': ['-joining_date', '-created_at'],
            },
        ),
    ]
