# Generated by Django 5.2.17 on 2026-10-02 09:45

import django.core.validators
import frontend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_expensecategory_alter_expenserecord_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiringrecord',
            name='allowance',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='hiringrecord',
            name='application_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hiringrecord',
            name='assigned_employee_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='hiringrecord',
            name='basic_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='hiringrecord',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hiringrecord',
            name='commission_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='hiringrecord',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hiringrecord',
            name='father_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='hiringrecord',
            name='home_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='hiringrecord',
            name='hr_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='hiringrecord',
            name='hr_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='hiringrecord',
            name='job_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='hiringrecord',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='hiringrecord',
            name='monthly_target',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='hiringrecord',
            name='nationality',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='hiringrecord',
            name='passport_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hiringrecord',
            name='passport_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='hiringrecord',
            name='passport_photo',
            field=models.FileField(blank=True, upload_to=frontend.models.joining_photo_upload_path),
        ),
        migrations.AddField(
            model_name='hiringrecord',
            name='room_provided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hiringrecord',
            name='secondary_home_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='hiringrecord',
            name='secondary_mobile_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='hiringrecord',
            name='secondary_whatsapp_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='hiringrecord',
            name='starting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hiringrecord',
            name='training_period',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='hiringrecord',
            name='visa_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='hiringrecord',
            name='visa_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hiringrecord',
            name='visa_status',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='hiringrecord',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
