# Generated by Django 5.2.17 on 2026-10-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_hiringrecord_allowance_hiringrecord_application_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiringrecord',
            name='citizenship_number',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
