# Generated by Django 5.2.17 on 2026-10-04 04:44

import django.core.validators
import django.db.models.deletion
import frontend.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_hiringrecord_citizenship_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='expenserecord',
            options={'ordering': ['-bill_date', '-created_at']},
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='amount_before_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='attachment',
            field=models.FileField(blank=True, upload_to=frontend.models.billing_document_upload_path),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='citizenship_number',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='current_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('probation', 'Probation'), ('temporary', 'Temporary'), ('intern', 'Intern')], default='full_time', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=16),
        ),
        migrations.AddField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('other', 'Other')], max_length=16),
        ),
        migrations.AddField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='employee',
            name='national_id_number',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='employee',
            name='pan_tax_number',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_number',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='employee',
            name='permanent_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_photo',
            field=models.FileField(blank=True, upload_to=frontend.models.employee_photo_upload_path),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='employee',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='frontend.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_location',
            field=models.CharField(blank=True, default='Dubai, UAE', max_length=120),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='category_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_records', to='frontend.expensecategory'),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='frontend.employee'),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='invoice_file',
            field=models.FileField(blank=True, upload_to=frontend.models.expense_invoice_upload_path),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('cheque', 'Cheque'), ('online', 'Online Payment'), ('other', 'Other')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='receipt_file',
            field=models.FileField(blank=True, upload_to=frontend.models.expense_receipt_upload_path),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='billingrecord',
            name='bill_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='billingrecord',
            name='client_name',
            field=models.CharField(db_index=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='billingrecord',
            name='invoice_number',
            field=models.CharField(db_index=True, max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='billingrecord',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='employee',
            name='destination',
            field=models.CharField(blank=True, default='Dubai, UAE', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(db_index=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nationality',
            field=models.CharField(blank=True, default='Nepali', max_length=80),
        ),
        migrations.AlterField(
            model_name='employee',
            name='origin_country',
            field=models.CharField(blank=True, default='Nepal', max_length=80),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('on_leave', 'On leave'), ('suspended', 'Suspended'), ('resigned', 'Resigned'), ('terminated', 'Terminated'), ('retired', 'Retired'), ('completed', 'Completed')], db_index=True, default='active', max_length=16),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='category',
            field=models.CharField(choices=[('passport', 'Passport'), ('photo', 'Photo'), ('contract', 'Contract'), ('visa', 'Visa'), ('certificate', 'Certificate'), ('id_card', 'ID Card'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='expenserecord',
            name='bill_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='expenserecord',
            name='category',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='expenserecord',
            name='reference_number',
            field=models.CharField(blank=True, db_index=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='expenserecord',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('unpaid', 'Unpaid'), ('overdue', 'Overdue')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='expenserecord',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='hiringrecord',
            name='client_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='hiringrecord',
            name='hiring_person_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('approve', 'Approved'), ('reject', 'Rejected'), ('mark_paid', 'Marked as Paid'), ('upload', 'Uploaded Document'), ('export', 'Exported Data'), ('print', 'Printed Record')], max_length=20)),
                ('model_name', models.CharField(max_length=60)),
                ('object_id', models.CharField(blank=True, max_length=60)),
                ('object_repr', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='frontend.department'),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='frontend.department'),
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designations', to='frontend.department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='frontend.designation'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('hr', 'HR Specialist'), ('finance', 'Finance & Accounts'), ('manager', 'Operations Manager'), ('employee', 'Standard Employee')], default='admin', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
